# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('timePosted', models.DateTimeField(auto_now_add=True)),
                ('postType', models.CharField(choices=[('DR', 'driver'), ('PA', 'passenger')], max_length=20)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('emptySeats', models.IntegerField()),
                ('passengerCapacity', models.IntegerField()),
                ('status', models.CharField(choices=[('F', 'Full'), ('A', 'Available')], max_length=20)),
            ],
        ),
    ]
