# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customUsers', '0003_auto_20170124_0253'),
        ('posts', '0002_auto_20170124_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customUsers.CustomUser'),
            preserve_default=False,
        ),
    ]
