# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customUsers', '0003_auto_20170124_0253'),
        ('posts', '0004_post_traveldate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='customUsers.CustomUser')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger', to='customUsers.CustomUser')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='posts.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, default='')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='posts.Request')),
            ],
        ),
    ]
