# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customUsers', '0003_auto_20170124_0253'),
        ('posts', '0005_request_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='customUsers.CustomUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customUsers.CustomUser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='posts.Request'),
        ),
    ]
