# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20170407_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='posts.Post'),
        ),
    ]
