# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20170407_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='emptySeats',
            new_name='totalPassengers',
        ),
        migrations.AddField(
            model_name='post',
            name='parent_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_posts', to='posts.Post'),
        ),
    ]
