# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='parent_post',
        ),
        migrations.AddField(
            model_name='request',
            name='driver_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_requests', to='posts.Post'),
        ),
        migrations.AddField(
            model_name='request',
            name='passengers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
