# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20170418_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedrequest',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_requests', to='posts.Post'),
        ),
        migrations.AlterField(
            model_name='confirmedrequest',
            name='request',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='posts.Request'),
            preserve_default=False,
        ),
    ]
