# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20170418_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='accepted',
            field=models.NullBooleanField(),
        ),
    ]
