# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_request_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='accepted',
            field=models.NullBooleanField(default=None),
        ),
    ]
